apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: external-secrets
      targetRevision: 0.9.13 
      repoURL: https://charts.external-secrets.io
      helm:
        releaseName: external-secrets
        valueFiles:
          - values.yaml
    - path: awx
      targetRevision: main
      repoURL: https://github.com/himanshusharma-git/awx-migration.git
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    name: in-cluster
    namespace: awx
