apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awx-migration
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - path: ESO
      targetRevision: main
      repoURL: https://github.com/himanshusharma-git/awx-migration.git
    - path: awx
      targetRevision: main
      repoURL: https://github.com/himanshusharma-git/awx-migration.git
    - path: external-secrets
      repoURL: https://github.com/himanshusharma-git/awx-migration.git
      targetRevision: main
      helm:
        valueFiles:
          - values.yaml
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  destination:
    name: in-cluster
    namespace: awx
