apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awx-sbx-admin-password
  namespace: awx
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: awx-sbx-admin-password
    creationPolicy: Owner
    template:
      data:
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: /admin/awx/sbx/bwahmed/postgres

