apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awx-sbx-secret-key
  namespace: awx
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: awx-sbx-secret-key
    creationPolicy: Owner
    template:
      data:
        secret_key: "{{ .secretkey }}"
  data:
  - secretKey: secretkey
    remoteRef:
      key: /admin/awx/sbx/bwahmed/secretkey

