apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-sbx
  namespace: awx
spec:
  service_type: LoadBalancer
  loadbalancer_protocol: http
  loadbalancer_port: 80
  service_annotations: |
    environment: sbx
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
  service_labels: |
    environment: sbx
    app: awx
  ingress_type: none
  postgres_configuration_secret: awx-sbx-postgres-configuration
  garbage_collect_secrets: true
  web_resource_requirements:
    requests:
      cpu: "1000m"
      memory: "1Gi"
    limits:
      cpu: "5000m"
      memory: "5Gi"
  task_resource_requirements:
    requests:
      cpu: "1000m"
      memory: "1Gi"
    limits:
      cpu: "5000m"
      memory: "5Gi"
  ee_resource_requirements:
    requests:
      cpu: "1000m"
      memory: "1Gi"
    limits:
      cpu: "5000m"
      memory: "5Gi"
